// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1ah0_gTrVkZYcWXFV5HUZjPxtPe-_Hs',
    appId: '1:998991701958:web:6e580c72098862067834c7',
    messagingSenderId: '998991701958',
    projectId: 'dibzz-47d45',
    authDomain: 'dibzz-47d45.firebaseapp.com',
    storageBucket: 'dibzz-47d45.appspot.com',
    measurementId: 'G-KH12DKPJ8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApNcqRRQ7POvXHdUfXtxJ1WA7vDmLSLno',
    appId: '1:998991701958:android:a84ca75f1bfa02ad7834c7',
    messagingSenderId: '998991701958',
    projectId: 'dibzz-47d45',
    storageBucket: 'dibzz-47d45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhhhfCa2278EGKv0fKZEQZ80FMvK5hLo0',
    appId: '1:998991701958:ios:a9d7e8aa1d8be56a7834c7',
    messagingSenderId: '998991701958',
    projectId: 'dibzz-47d45',
    storageBucket: 'dibzz-47d45.appspot.com',
    iosClientId: '998991701958-slk8l0av1rv90mp2cbnsrqrjahc23r47.apps.googleusercontent.com',
    iosBundleId: 'com.example.gui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhhhfCa2278EGKv0fKZEQZ80FMvK5hLo0',
    appId: '1:998991701958:ios:a9d7e8aa1d8be56a7834c7',
    messagingSenderId: '998991701958',
    projectId: 'dibzz-47d45',
    storageBucket: 'dibzz-47d45.appspot.com',
    iosClientId: '998991701958-slk8l0av1rv90mp2cbnsrqrjahc23r47.apps.googleusercontent.com',
    iosBundleId: 'com.example.gui',
  );
}
